/**
 * Autogenerated by Thrift for /home/adrien/Documents/epfl/MA/cs-471/project/dep/if/chatroom.thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated @nocommit
 */
#pragma once

#include <thrift/lib/cpp2/gen/client_h.h>

#include "if/gen-cpp2/chatroom_types.h"

namespace apache { namespace thrift {
  class Cpp2RequestContext;
  namespace detail { namespace ac { struct ClientRequestContext; }}
  namespace transport { class THeader; }
}}

namespace example { namespace chatroom {

class ChatRoomServiceAsyncClient : public apache::thrift::GeneratedAsyncClient {
 public:
  using apache::thrift::GeneratedAsyncClient::GeneratedAsyncClient;

  char const* getServiceName() const noexcept override {
    return "ChatRoomService";
  }


  virtual void initialize(std::unique_ptr<apache::thrift::RequestCallback> callback);
  virtual void initialize(apache::thrift::RpcOptions& rpcOptions, std::unique_ptr<apache::thrift::RequestCallback> callback);
 protected:
  void initializeImpl(apache::thrift::RpcOptions& rpcOptions, std::shared_ptr<apache::thrift::transport::THeader> header, apache::thrift::ContextStack* contextStack, apache::thrift::RequestClientCallback::Ptr callback, bool stealRpcOptions = false);
 public:

  virtual void sync_initialize();
  virtual void sync_initialize(apache::thrift::RpcOptions& rpcOptions);

  virtual folly::Future<folly::Unit> future_initialize();
  virtual folly::SemiFuture<folly::Unit> semifuture_initialize();
  virtual folly::Future<folly::Unit> future_initialize(apache::thrift::RpcOptions& rpcOptions);
  virtual folly::SemiFuture<folly::Unit> semifuture_initialize(apache::thrift::RpcOptions& rpcOptions);
  virtual folly::Future<std::pair<folly::Unit, std::unique_ptr<apache::thrift::transport::THeader>>> header_future_initialize(apache::thrift::RpcOptions& rpcOptions);
  virtual folly::SemiFuture<std::pair<folly::Unit, std::unique_ptr<apache::thrift::transport::THeader>>> header_semifuture_initialize(apache::thrift::RpcOptions& rpcOptions);

#if FOLLY_HAS_COROUTINES
  template <int = 0>
  folly::coro::Task<void> co_initialize() {
    return co_initialize<false>(nullptr);
  }
  template <int = 0>
  folly::coro::Task<void> co_initialize(apache::thrift::RpcOptions& rpcOptions) {
    return co_initialize<true>(&rpcOptions);
  }
 private:
  template <bool hasRpcOptions>
  folly::coro::Task<void> co_initialize(apache::thrift::RpcOptions* rpcOptions) {
    const folly::CancellationToken& cancelToken =
        co_await folly::coro::co_current_cancellation_token;
    const bool cancellable = cancelToken.canBeCancelled();
    apache::thrift::ClientReceiveState returnState;
    apache::thrift::ClientSyncCallback<false> callback(&returnState);
    auto protocolId = apache::thrift::GeneratedAsyncClient::getChannel()->getProtocolId();
    auto [ctx, header] = initializeCtx(rpcOptions);
    using CancellableCallback = apache::thrift::CancellableRequestClientCallback<false>;
    auto cancellableCallback = cancellable ? CancellableCallback::create(&callback, channel_) : nullptr;
    static apache::thrift::RpcOptions defaultRpcOptions;
    auto wrappedCallback = apache::thrift::RequestClientCallback::Ptr(cancellableCallback ? (apache::thrift::RequestClientCallback*)cancellableCallback.get() : &callback);
    if constexpr (hasRpcOptions) {
      initializeImpl(*rpcOptions, std::move(header), ctx.get(), std::move(wrappedCallback));
    } else {
      initializeImpl(defaultRpcOptions, std::move(header), ctx.get(), std::move(wrappedCallback));
    }
    if (cancellable) {
      folly::CancellationCallback cb(cancelToken, [&] { CancellableCallback::cancel(std::move(cancellableCallback)); });
      co_await callback.co_waitUntilDone();
    } else {
      co_await callback.co_waitUntilDone();
    }
    if (returnState.isException()) {
      co_yield folly::coro::co_error(std::move(returnState.exception()));
    }
    returnState.resetProtocolId(protocolId);
    returnState.resetCtx(std::move(ctx));
    SCOPE_EXIT {
      if (hasRpcOptions && returnState.header()) {
        auto* rheader = returnState.header();
        if (!rheader->getHeaders().empty()) {
          rpcOptions->setReadHeaders(rheader->releaseHeaders());
        }
        rpcOptions->setRoutingData(rheader->releaseRoutingData());
      }
    };
    if (auto ew = recv_wrapped_initialize(returnState)) {
      co_yield folly::coro::co_error(std::move(ew));
    }
  }
 public:
#endif // FOLLY_HAS_COROUTINES

  virtual void initialize(folly::Function<void (::apache::thrift::ClientReceiveState&&)> callback);


  static folly::exception_wrapper recv_wrapped_initialize(::apache::thrift::ClientReceiveState& state);
  static void recv_initialize(::apache::thrift::ClientReceiveState& state);
  // Mock friendly virtual instance method
  virtual void recv_instance_initialize(::apache::thrift::ClientReceiveState& state);
  virtual folly::exception_wrapper recv_instance_wrapped_initialize(::apache::thrift::ClientReceiveState& state);
 private:
  template <typename Protocol_, typename RpcOptions>
  void initializeT(Protocol_* prot, RpcOptions&& rpcOptions, std::shared_ptr<apache::thrift::transport::THeader> header, apache::thrift::ContextStack* contextStack, apache::thrift::RequestClientCallback::Ptr callback);
  std::pair<std::unique_ptr<::apache::thrift::ContextStack>, std::shared_ptr<::apache::thrift::transport::THeader>> initializeCtx(apache::thrift::RpcOptions* rpcOptions);
 public:
  virtual void getMessages(std::unique_ptr<apache::thrift::RequestCallback> callback, const ::example::chatroom::GetMessagesRequest& p_req);
  virtual void getMessages(apache::thrift::RpcOptions& rpcOptions, std::unique_ptr<apache::thrift::RequestCallback> callback, const ::example::chatroom::GetMessagesRequest& p_req);
 protected:
  void getMessagesImpl(apache::thrift::RpcOptions& rpcOptions, std::shared_ptr<apache::thrift::transport::THeader> header, apache::thrift::ContextStack* contextStack, apache::thrift::RequestClientCallback::Ptr callback, const ::example::chatroom::GetMessagesRequest& p_req, bool stealRpcOptions = false);
 public:

  virtual void sync_getMessages(::example::chatroom::GetMessagesResponse& _return, const ::example::chatroom::GetMessagesRequest& p_req);
  virtual void sync_getMessages(apache::thrift::RpcOptions& rpcOptions, ::example::chatroom::GetMessagesResponse& _return, const ::example::chatroom::GetMessagesRequest& p_req);

  virtual folly::Future<::example::chatroom::GetMessagesResponse> future_getMessages(const ::example::chatroom::GetMessagesRequest& p_req);
  virtual folly::SemiFuture<::example::chatroom::GetMessagesResponse> semifuture_getMessages(const ::example::chatroom::GetMessagesRequest& p_req);
  virtual folly::Future<::example::chatroom::GetMessagesResponse> future_getMessages(apache::thrift::RpcOptions& rpcOptions, const ::example::chatroom::GetMessagesRequest& p_req);
  virtual folly::SemiFuture<::example::chatroom::GetMessagesResponse> semifuture_getMessages(apache::thrift::RpcOptions& rpcOptions, const ::example::chatroom::GetMessagesRequest& p_req);
  virtual folly::Future<std::pair<::example::chatroom::GetMessagesResponse, std::unique_ptr<apache::thrift::transport::THeader>>> header_future_getMessages(apache::thrift::RpcOptions& rpcOptions, const ::example::chatroom::GetMessagesRequest& p_req);
  virtual folly::SemiFuture<std::pair<::example::chatroom::GetMessagesResponse, std::unique_ptr<apache::thrift::transport::THeader>>> header_semifuture_getMessages(apache::thrift::RpcOptions& rpcOptions, const ::example::chatroom::GetMessagesRequest& p_req);

#if FOLLY_HAS_COROUTINES
  template <int = 0>
  folly::coro::Task<::example::chatroom::GetMessagesResponse> co_getMessages(const ::example::chatroom::GetMessagesRequest& p_req) {
    return co_getMessages<false>(nullptr, p_req);
  }
  template <int = 0>
  folly::coro::Task<::example::chatroom::GetMessagesResponse> co_getMessages(apache::thrift::RpcOptions& rpcOptions, const ::example::chatroom::GetMessagesRequest& p_req) {
    return co_getMessages<true>(&rpcOptions, p_req);
  }
 private:
  template <bool hasRpcOptions>
  folly::coro::Task<::example::chatroom::GetMessagesResponse> co_getMessages(apache::thrift::RpcOptions* rpcOptions, const ::example::chatroom::GetMessagesRequest& p_req) {
    const folly::CancellationToken& cancelToken =
        co_await folly::coro::co_current_cancellation_token;
    const bool cancellable = cancelToken.canBeCancelled();
    apache::thrift::ClientReceiveState returnState;
    apache::thrift::ClientSyncCallback<false> callback(&returnState);
    auto protocolId = apache::thrift::GeneratedAsyncClient::getChannel()->getProtocolId();
    auto [ctx, header] = getMessagesCtx(rpcOptions);
    using CancellableCallback = apache::thrift::CancellableRequestClientCallback<false>;
    auto cancellableCallback = cancellable ? CancellableCallback::create(&callback, channel_) : nullptr;
    static apache::thrift::RpcOptions defaultRpcOptions;
    auto wrappedCallback = apache::thrift::RequestClientCallback::Ptr(cancellableCallback ? (apache::thrift::RequestClientCallback*)cancellableCallback.get() : &callback);
    if constexpr (hasRpcOptions) {
      getMessagesImpl(*rpcOptions, std::move(header), ctx.get(), std::move(wrappedCallback), p_req);
    } else {
      getMessagesImpl(defaultRpcOptions, std::move(header), ctx.get(), std::move(wrappedCallback), p_req);
    }
    if (cancellable) {
      folly::CancellationCallback cb(cancelToken, [&] { CancellableCallback::cancel(std::move(cancellableCallback)); });
      co_await callback.co_waitUntilDone();
    } else {
      co_await callback.co_waitUntilDone();
    }
    if (returnState.isException()) {
      co_yield folly::coro::co_error(std::move(returnState.exception()));
    }
    returnState.resetProtocolId(protocolId);
    returnState.resetCtx(std::move(ctx));
    SCOPE_EXIT {
      if (hasRpcOptions && returnState.header()) {
        auto* rheader = returnState.header();
        if (!rheader->getHeaders().empty()) {
          rpcOptions->setReadHeaders(rheader->releaseHeaders());
        }
        rpcOptions->setRoutingData(rheader->releaseRoutingData());
      }
    };
    ::example::chatroom::GetMessagesResponse _return;
    if (auto ew = recv_wrapped_getMessages(_return, returnState)) {
      co_yield folly::coro::co_error(std::move(ew));
    }
    co_return _return;
  }
 public:
#endif // FOLLY_HAS_COROUTINES

  virtual void getMessages(folly::Function<void (::apache::thrift::ClientReceiveState&&)> callback, const ::example::chatroom::GetMessagesRequest& p_req);


  static folly::exception_wrapper recv_wrapped_getMessages(::example::chatroom::GetMessagesResponse& _return, ::apache::thrift::ClientReceiveState& state);
  static void recv_getMessages(::example::chatroom::GetMessagesResponse& _return, ::apache::thrift::ClientReceiveState& state);
  // Mock friendly virtual instance method
  virtual void recv_instance_getMessages(::example::chatroom::GetMessagesResponse& _return, ::apache::thrift::ClientReceiveState& state);
  virtual folly::exception_wrapper recv_instance_wrapped_getMessages(::example::chatroom::GetMessagesResponse& _return, ::apache::thrift::ClientReceiveState& state);
 private:
  template <typename Protocol_, typename RpcOptions>
  void getMessagesT(Protocol_* prot, RpcOptions&& rpcOptions, std::shared_ptr<apache::thrift::transport::THeader> header, apache::thrift::ContextStack* contextStack, apache::thrift::RequestClientCallback::Ptr callback, const ::example::chatroom::GetMessagesRequest& p_req);
  std::pair<std::unique_ptr<::apache::thrift::ContextStack>, std::shared_ptr<::apache::thrift::transport::THeader>> getMessagesCtx(apache::thrift::RpcOptions* rpcOptions);
 public:
  virtual void sendMessage(std::unique_ptr<apache::thrift::RequestCallback> callback, const ::example::chatroom::SendMessageRequest& p_req);
  virtual void sendMessage(apache::thrift::RpcOptions& rpcOptions, std::unique_ptr<apache::thrift::RequestCallback> callback, const ::example::chatroom::SendMessageRequest& p_req);
 protected:
  void sendMessageImpl(apache::thrift::RpcOptions& rpcOptions, std::shared_ptr<apache::thrift::transport::THeader> header, apache::thrift::ContextStack* contextStack, apache::thrift::RequestClientCallback::Ptr callback, const ::example::chatroom::SendMessageRequest& p_req, bool stealRpcOptions = false);
 public:

  virtual void sync_sendMessage(const ::example::chatroom::SendMessageRequest& p_req);
  virtual void sync_sendMessage(apache::thrift::RpcOptions& rpcOptions, const ::example::chatroom::SendMessageRequest& p_req);

  virtual folly::Future<folly::Unit> future_sendMessage(const ::example::chatroom::SendMessageRequest& p_req);
  virtual folly::SemiFuture<folly::Unit> semifuture_sendMessage(const ::example::chatroom::SendMessageRequest& p_req);
  virtual folly::Future<folly::Unit> future_sendMessage(apache::thrift::RpcOptions& rpcOptions, const ::example::chatroom::SendMessageRequest& p_req);
  virtual folly::SemiFuture<folly::Unit> semifuture_sendMessage(apache::thrift::RpcOptions& rpcOptions, const ::example::chatroom::SendMessageRequest& p_req);
  virtual folly::Future<std::pair<folly::Unit, std::unique_ptr<apache::thrift::transport::THeader>>> header_future_sendMessage(apache::thrift::RpcOptions& rpcOptions, const ::example::chatroom::SendMessageRequest& p_req);
  virtual folly::SemiFuture<std::pair<folly::Unit, std::unique_ptr<apache::thrift::transport::THeader>>> header_semifuture_sendMessage(apache::thrift::RpcOptions& rpcOptions, const ::example::chatroom::SendMessageRequest& p_req);

#if FOLLY_HAS_COROUTINES
  template <int = 0>
  folly::coro::Task<void> co_sendMessage(const ::example::chatroom::SendMessageRequest& p_req) {
    return co_sendMessage<false>(nullptr, p_req);
  }
  template <int = 0>
  folly::coro::Task<void> co_sendMessage(apache::thrift::RpcOptions& rpcOptions, const ::example::chatroom::SendMessageRequest& p_req) {
    return co_sendMessage<true>(&rpcOptions, p_req);
  }
 private:
  template <bool hasRpcOptions>
  folly::coro::Task<void> co_sendMessage(apache::thrift::RpcOptions* rpcOptions, const ::example::chatroom::SendMessageRequest& p_req) {
    const folly::CancellationToken& cancelToken =
        co_await folly::coro::co_current_cancellation_token;
    const bool cancellable = cancelToken.canBeCancelled();
    apache::thrift::ClientReceiveState returnState;
    apache::thrift::ClientSyncCallback<false> callback(&returnState);
    auto protocolId = apache::thrift::GeneratedAsyncClient::getChannel()->getProtocolId();
    auto [ctx, header] = sendMessageCtx(rpcOptions);
    using CancellableCallback = apache::thrift::CancellableRequestClientCallback<false>;
    auto cancellableCallback = cancellable ? CancellableCallback::create(&callback, channel_) : nullptr;
    static apache::thrift::RpcOptions defaultRpcOptions;
    auto wrappedCallback = apache::thrift::RequestClientCallback::Ptr(cancellableCallback ? (apache::thrift::RequestClientCallback*)cancellableCallback.get() : &callback);
    if constexpr (hasRpcOptions) {
      sendMessageImpl(*rpcOptions, std::move(header), ctx.get(), std::move(wrappedCallback), p_req);
    } else {
      sendMessageImpl(defaultRpcOptions, std::move(header), ctx.get(), std::move(wrappedCallback), p_req);
    }
    if (cancellable) {
      folly::CancellationCallback cb(cancelToken, [&] { CancellableCallback::cancel(std::move(cancellableCallback)); });
      co_await callback.co_waitUntilDone();
    } else {
      co_await callback.co_waitUntilDone();
    }
    if (returnState.isException()) {
      co_yield folly::coro::co_error(std::move(returnState.exception()));
    }
    returnState.resetProtocolId(protocolId);
    returnState.resetCtx(std::move(ctx));
    SCOPE_EXIT {
      if (hasRpcOptions && returnState.header()) {
        auto* rheader = returnState.header();
        if (!rheader->getHeaders().empty()) {
          rpcOptions->setReadHeaders(rheader->releaseHeaders());
        }
        rpcOptions->setRoutingData(rheader->releaseRoutingData());
      }
    };
    if (auto ew = recv_wrapped_sendMessage(returnState)) {
      co_yield folly::coro::co_error(std::move(ew));
    }
  }
 public:
#endif // FOLLY_HAS_COROUTINES

  virtual void sendMessage(folly::Function<void (::apache::thrift::ClientReceiveState&&)> callback, const ::example::chatroom::SendMessageRequest& p_req);


  static folly::exception_wrapper recv_wrapped_sendMessage(::apache::thrift::ClientReceiveState& state);
  static void recv_sendMessage(::apache::thrift::ClientReceiveState& state);
  // Mock friendly virtual instance method
  virtual void recv_instance_sendMessage(::apache::thrift::ClientReceiveState& state);
  virtual folly::exception_wrapper recv_instance_wrapped_sendMessage(::apache::thrift::ClientReceiveState& state);
 private:
  template <typename Protocol_, typename RpcOptions>
  void sendMessageT(Protocol_* prot, RpcOptions&& rpcOptions, std::shared_ptr<apache::thrift::transport::THeader> header, apache::thrift::ContextStack* contextStack, apache::thrift::RequestClientCallback::Ptr callback, const ::example::chatroom::SendMessageRequest& p_req);
  std::pair<std::unique_ptr<::apache::thrift::ContextStack>, std::shared_ptr<::apache::thrift::transport::THeader>> sendMessageCtx(apache::thrift::RpcOptions* rpcOptions);
 public:
};

}} // example::chatroom
