/**
 * Autogenerated by Thrift for /home/adrien/Documents/epfl/MA/cs-471/project/dep/if/chatroom.thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated @nocommit
 */

#include "if/gen-cpp2/chatroom_data.h"

#include <thrift/lib/cpp2/gen/module_data_cpp.h>

namespace apache {
namespace thrift {

const std::array<folly::StringPiece, 3> TStructDataStorage<::example::chatroom::Message>::fields_names = {{
  "message",
  "sender",
  "timestamp",
}};
const std::array<int16_t, 3> TStructDataStorage<::example::chatroom::Message>::fields_ids = {{
  1,
  2,
  3,
}};
const std::array<protocol::TType, 3> TStructDataStorage<::example::chatroom::Message>::fields_types = {{
  TType::T_STRING,
  TType::T_STRING,
  TType::T_I64,
}};

const std::array<folly::StringPiece, 1> TStructDataStorage<::example::chatroom::IndexToken>::fields_names = {{
  "index",
}};
const std::array<int16_t, 1> TStructDataStorage<::example::chatroom::IndexToken>::fields_ids = {{
  1,
}};
const std::array<protocol::TType, 1> TStructDataStorage<::example::chatroom::IndexToken>::fields_types = {{
  TType::T_I64,
}};

const std::array<folly::StringPiece, 1> TStructDataStorage<::example::chatroom::GetMessagesRequest>::fields_names = {{
  "token",
}};
const std::array<int16_t, 1> TStructDataStorage<::example::chatroom::GetMessagesRequest>::fields_ids = {{
  1,
}};
const std::array<protocol::TType, 1> TStructDataStorage<::example::chatroom::GetMessagesRequest>::fields_types = {{
  TType::T_STRUCT,
}};

const std::array<folly::StringPiece, 2> TStructDataStorage<::example::chatroom::GetMessagesResponse>::fields_names = {{
  "messages",
  "token",
}};
const std::array<int16_t, 2> TStructDataStorage<::example::chatroom::GetMessagesResponse>::fields_ids = {{
  1,
  2,
}};
const std::array<protocol::TType, 2> TStructDataStorage<::example::chatroom::GetMessagesResponse>::fields_types = {{
  TType::T_LIST,
  TType::T_STRUCT,
}};

const std::array<folly::StringPiece, 2> TStructDataStorage<::example::chatroom::SendMessageRequest>::fields_names = {{
  "message",
  "sender",
}};
const std::array<int16_t, 2> TStructDataStorage<::example::chatroom::SendMessageRequest>::fields_ids = {{
  1,
  2,
}};
const std::array<protocol::TType, 2> TStructDataStorage<::example::chatroom::SendMessageRequest>::fields_types = {{
  TType::T_STRING,
  TType::T_STRING,
}};

const std::array<folly::StringPiece, 1> TStructDataStorage<::example::chatroom::Exception>::fields_names = {{
  "message",
}};
const std::array<int16_t, 1> TStructDataStorage<::example::chatroom::Exception>::fields_ids = {{
  1,
}};
const std::array<protocol::TType, 1> TStructDataStorage<::example::chatroom::Exception>::fields_types = {{
  TType::T_STRING,
}};

} // namespace thrift
} // namespace apache
