/**
 * Autogenerated by Thrift for /home/adrien/Documents/epfl/MA/cs-471/project/dep/if/chatroom.thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated @nocommit
 */
#pragma once
#include "if/gen-cpp2/chatroom_for_each_field.h"
#include "if/gen-cpp2/chatroom_visit_union.h"
#include "if/gen-cpp2/chatroom_visit_by_thrift_field_metadata.h"
