/**
 * Autogenerated by Thrift for /home/adrien/Documents/epfl/MA/cs-471/project/dep/if/chatroom.thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated @nocommit
 */

#include "if/gen-cpp2/ChatRoomService.h"
#include "if/gen-cpp2/ChatRoomService.tcc"

namespace example { namespace chatroom {
}} // example::chatroom
