/**
 * Autogenerated by Thrift for /home/adrien/Documents/epfl/MA/cs-471/project/dep/if/chatroom.thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated @nocommit
 */

#include "if/gen-cpp2/EchoAsyncClient.h"

#include <thrift/lib/cpp2/gen/client_cpp.h>

namespace example { namespace chatroom {
typedef apache::thrift::ThriftPresult<false, apache::thrift::FieldData<1, ::apache::thrift::type_class::string, ::std::string*>> Echo_echo_pargs;
typedef apache::thrift::ThriftPresult<true, apache::thrift::FieldData<0, ::apache::thrift::type_class::string, ::std::string*>> Echo_echo_presult;

template <typename Protocol_, typename RpcOptions>
void EchoAsyncClient::echoT(Protocol_* prot, RpcOptions&& rpcOptions, std::shared_ptr<apache::thrift::transport::THeader> header, apache::thrift::ContextStack* contextStack, apache::thrift::RequestClientCallback::Ptr callback, const ::std::string& p_message) {

  Echo_echo_pargs args;
  args.get<0>().value = const_cast<::std::string*>(&p_message);
  auto sizer = [&](Protocol_* p) { return args.serializedSizeZC(p); };
  auto writer = [&](Protocol_* p) { args.write(p); };

  static ::apache::thrift::MethodMetadata::Data* methodMetadata =
        new ::apache::thrift::MethodMetadata::Data(
                "echo",
                ::apache::thrift::FunctionQualifier::Unspecified);
  apache::thrift::clientSendT<apache::thrift::RpcKind::SINGLE_REQUEST_SINGLE_RESPONSE, Protocol_>(prot, std::forward<RpcOptions>(rpcOptions), std::move(callback), contextStack, std::move(header), channel_.get(), ::apache::thrift::MethodMetadata::from_static(methodMetadata), writer, sizer);
}



void EchoAsyncClient::echo(std::unique_ptr<apache::thrift::RequestCallback> callback, const ::std::string& p_message) {
  ::apache::thrift::RpcOptions rpcOptions;
  echo(rpcOptions, std::move(callback), p_message);
}

void EchoAsyncClient::echo(apache::thrift::RpcOptions& rpcOptions, std::unique_ptr<apache::thrift::RequestCallback> callback, const ::std::string& p_message) {
  auto [ctx, header] = echoCtx(&rpcOptions);
  apache::thrift::RequestCallback::Context callbackContext;
  callbackContext.protocolId =
      apache::thrift::GeneratedAsyncClient::getChannel()->getProtocolId();
  auto* contextStack = ctx.get();
  if (callback) {
    callbackContext.ctx = std::move(ctx);
  }
  auto wrappedCallback = apache::thrift::toRequestClientCallbackPtr(std::move(callback), std::move(callbackContext));
  echoImpl(rpcOptions, std::move(header), contextStack, std::move(wrappedCallback), p_message);
}

void EchoAsyncClient::echoImpl(apache::thrift::RpcOptions& rpcOptions, std::shared_ptr<apache::thrift::transport::THeader> header, apache::thrift::ContextStack* contextStack, apache::thrift::RequestClientCallback::Ptr callback, const ::std::string& p_message, bool stealRpcOptions) {
  switch (apache::thrift::GeneratedAsyncClient::getChannel()->getProtocolId()) {
    case apache::thrift::protocol::T_BINARY_PROTOCOL:
    {
      apache::thrift::BinaryProtocolWriter writer;
      if (stealRpcOptions) {
        echoT(&writer, std::move(rpcOptions), std::move(header), contextStack, std::move(callback), p_message);
      } else {
        echoT(&writer, rpcOptions, std::move(header), contextStack, std::move(callback), p_message);
      }
      break;
    }
    case apache::thrift::protocol::T_COMPACT_PROTOCOL:
    {
      apache::thrift::CompactProtocolWriter writer;
      if (stealRpcOptions) {
        echoT(&writer, std::move(rpcOptions), std::move(header), contextStack, std::move(callback), p_message);
      } else {
        echoT(&writer, rpcOptions, std::move(header), contextStack, std::move(callback), p_message);
      }
      break;
    }
    default:
    {
      apache::thrift::detail::ac::throw_app_exn("Could not find Protocol");
    }
  }
}

std::pair<std::unique_ptr<::apache::thrift::ContextStack>, std::shared_ptr<::apache::thrift::transport::THeader>> EchoAsyncClient::echoCtx(apache::thrift::RpcOptions* rpcOptions) {
  auto header = std::make_shared<apache::thrift::transport::THeader>(
      apache::thrift::transport::THeader::ALLOW_BIG_FRAMES);
  header->setProtocolId(channel_->getProtocolId());
  if (rpcOptions) {
    header->setHeaders(rpcOptions->releaseWriteHeaders());
  }

  auto ctx = apache::thrift::ContextStack::createWithClientContext(
      handlers_,
      getServiceName(),
      "Echo.echo",
      *header);

  return {std::move(ctx), std::move(header)};
}

void EchoAsyncClient::sync_echo(::std::string& _return, const ::std::string& p_message) {
  ::apache::thrift::RpcOptions rpcOptions;
  sync_echo(rpcOptions, _return, p_message);
}

void EchoAsyncClient::sync_echo(apache::thrift::RpcOptions& rpcOptions, ::std::string& _return, const ::std::string& p_message) {
  apache::thrift::ClientReceiveState returnState;
  apache::thrift::ClientSyncCallback<false> callback(&returnState);
  auto protocolId = apache::thrift::GeneratedAsyncClient::getChannel()->getProtocolId();
  auto evb = apache::thrift::GeneratedAsyncClient::getChannel()->getEventBase();
  auto ctxAndHeader = echoCtx(&rpcOptions);
  auto wrappedCallback = apache::thrift::RequestClientCallback::Ptr(&callback);
  callback.waitUntilDone(
    evb,
    [&] {
      echoImpl(rpcOptions, std::move(ctxAndHeader.second), ctxAndHeader.first.get(), std::move(wrappedCallback), p_message);
    });

  if (returnState.isException()) {
    returnState.exception().throw_exception();
  }
  returnState.resetProtocolId(protocolId);
  returnState.resetCtx(std::move(ctxAndHeader.first));
  SCOPE_EXIT {
    if (returnState.header() && !returnState.header()->getHeaders().empty()) {
      rpcOptions.setReadHeaders(returnState.header()->releaseHeaders());
    }
  };
  return folly::fibers::runInMainContext([&] {
      recv_echo(_return, returnState);
  });
}


folly::Future<::std::string> EchoAsyncClient::future_echo(const ::std::string& p_message) {
  ::apache::thrift::RpcOptions rpcOptions;
  return future_echo(rpcOptions, p_message);
}

folly::SemiFuture<::std::string> EchoAsyncClient::semifuture_echo(const ::std::string& p_message) {
  ::apache::thrift::RpcOptions rpcOptions;
  return semifuture_echo(rpcOptions, p_message);
}

folly::Future<::std::string> EchoAsyncClient::future_echo(apache::thrift::RpcOptions& rpcOptions, const ::std::string& p_message) {
  folly::Promise<::std::string> promise;
  auto future = promise.getFuture();
  auto callback = std::make_unique<apache::thrift::FutureCallback<::std::string>>(std::move(promise), recv_wrapped_echo, channel_);
  echo(rpcOptions, std::move(callback), p_message);
  return future;
}

folly::SemiFuture<::std::string> EchoAsyncClient::semifuture_echo(apache::thrift::RpcOptions& rpcOptions, const ::std::string& p_message) {
  auto callbackAndFuture = makeSemiFutureCallback(recv_wrapped_echo, channel_);
  auto callback = std::move(callbackAndFuture.first);
  echo(rpcOptions, std::move(callback), p_message);
  return std::move(callbackAndFuture.second);
}

folly::Future<std::pair<::std::string, std::unique_ptr<apache::thrift::transport::THeader>>> EchoAsyncClient::header_future_echo(apache::thrift::RpcOptions& rpcOptions, const ::std::string& p_message) {
  folly::Promise<std::pair<::std::string, std::unique_ptr<apache::thrift::transport::THeader>>> promise;
  auto future = promise.getFuture();
  auto callback = std::make_unique<apache::thrift::HeaderFutureCallback<::std::string>>(std::move(promise), recv_wrapped_echo, channel_);
  echo(rpcOptions, std::move(callback), p_message);
  return future;
}

folly::SemiFuture<std::pair<::std::string, std::unique_ptr<apache::thrift::transport::THeader>>> EchoAsyncClient::header_semifuture_echo(apache::thrift::RpcOptions& rpcOptions, const ::std::string& p_message) {
  auto callbackAndFuture = makeHeaderSemiFutureCallback(recv_wrapped_echo, channel_);
  auto callback = std::move(callbackAndFuture.first);
  echo(rpcOptions, std::move(callback), p_message);
  return std::move(callbackAndFuture.second);
}

void EchoAsyncClient::echo(folly::Function<void (::apache::thrift::ClientReceiveState&&)> callback, const ::std::string& p_message) {
  echo(std::make_unique<apache::thrift::FunctionReplyCallback>(std::move(callback)), p_message);
}

#if FOLLY_HAS_COROUTINES
#endif // FOLLY_HAS_COROUTINES
folly::exception_wrapper EchoAsyncClient::recv_wrapped_echo(::std::string& _return, ::apache::thrift::ClientReceiveState& state) {
  if (state.isException()) {
    return std::move(state.exception());
  }
  if (!state.hasResponseBuffer()) {
    return folly::make_exception_wrapper<apache::thrift::TApplicationException>("recv_ called without result");
  }

  using result = Echo_echo_presult;
  switch (state.protocolId()) {
    case apache::thrift::protocol::T_BINARY_PROTOCOL:
    {
      apache::thrift::BinaryProtocolReader reader;
      return apache::thrift::detail::ac::recv_wrapped<result>(
          &reader, state, _return);
    }
    case apache::thrift::protocol::T_COMPACT_PROTOCOL:
    {
      apache::thrift::CompactProtocolReader reader;
      return apache::thrift::detail::ac::recv_wrapped<result>(
          &reader, state, _return);
    }
    default:
    {
    }
  }
  return folly::make_exception_wrapper<apache::thrift::TApplicationException>("Could not find Protocol");
}

void EchoAsyncClient::recv_echo(::std::string& _return, ::apache::thrift::ClientReceiveState& state) {
  auto ew = recv_wrapped_echo(_return, state);
  if (ew) {
    ew.throw_exception();
  }
}

void EchoAsyncClient::recv_instance_echo(::std::string& _return, ::apache::thrift::ClientReceiveState& state) {
  return recv_echo(_return, state);
}

folly::exception_wrapper EchoAsyncClient::recv_instance_wrapped_echo(::std::string& _return, ::apache::thrift::ClientReceiveState& state) {
  return recv_wrapped_echo(_return, state);
}


}} // example::chatroom
